#
# Distributed Linear Algebra with Future (DLAF)
#
# Copyright (c) 2018-2023, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#

spack:
  include:
  - /spack_environment/common.yaml

  view: false
  concretizer:
    unify:
      true

  specs:
    - dla-future@master build_type=Debug +cuda +miniapps +ci-test

  packages:
    all:
      variants:
        - 'build_type=Release'
    blas:
      require:: 'openblas'
    lapack:
      require:: 'openblas'
    pika:
      require:
        - 'build_type=Debug'
        - 'malloc=system'
    # For correct code coverage
    # https://github.com/eth-cscs/DLA-Future/pull/1002
    umpire:
      require: '@2022.03.1'
