#
# Distributed Linear Algebra with Future (DLAF)
#
# Copyright (c) 2018-2022, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#

spack:
  specs:
    - dla-future@develop +cuda +miniapps +ci-test ^intel-mkl ^mpich
  view: false
  concretization: together

  packages:
    all:
      target: [x86_64]
      variants:
        - 'build_type=Release'
        - 'cxxstd=17'
    blaspp:
      variants:
        - '~cuda'
        - '~openmp'
    mpich:
      variants:
        - '~fortran'
