#
# Distributed Linear Algebra with Future (DLAF)
#
# Copyright (c) 2018-2023, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#

spack:
  include:
  - common.yaml

  view: false
  concretizer:
    unify:
      true

  specs:
    - "dla-future@develop +cuda cmakeflags=\'-DCMAKE_CXX_FLAGS=-Werror -DCMAKE_CUDA_FLAGS=-Werror=all-warnings -DBUILD_TESTING=ON -DDLAF_BUILD_TESTING=ON -DDLAF_CI_RUNNER_USES_MPIRUN\' ^intel-mkl ^mpich"

  packages:
    all:
      variants:
        - 'build_type=Release'
