#
# Distributed Linear Algebra with Future (DLAF)
#
# Copyright (c) ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#
doc:
	sed 's|$${DLAF_SOURCE_DIR}|..|g' Doxyfile.in | doxygen -
