name: dlaf-env
store: /user-environment
spack:
    repo: https://github.com/msimberg/spack.git
    commit: dla-future-202410-develop
mirror:
    enable: false
modules: false
description: "DLA-Future for 202410 status update"
