#!/bin/bash

# Usage: `mpirun gpu2ranks_ompi <my_commands>`
#
# The script is used on the M100 cluster with IBM's Spectrum MPI implementation
# (but any other OpenMPI implementation should also work). `gpu2ranks_ompi`
# sets the environent variable `CUDA_VISIBLE_DEVICES` to ensure that ranks are
# only assigned to GPUs on the same socket and executes `<my_command>` 

if [ -z "${OMPI_COMM_WORLD_LOCAL_RANK}" ]
then
  echo "You need to run this script with `mpirun`!"
fi

export CUDA_VISIBLE_DEVICES=${OMPI_COMM_WORLD_LOCAL_RANK}

if [ ${OMPI_COMM_WORLD_LOCAL_RANK} -eq 1 ]
then
  export CUDA_VISIBLE_DEVICES=2
fi

if [ ${OMPI_COMM_WORLD_LOCAL_RANK} -eq 2 ]
then
  export CUDA_VISIBLE_DEVICES=1
fi

eval "$@"
