[project]
name = "dlaf-benchmarks"
version = "0.1.0"
description = "Utilities for running DLA-Future benchmarks."
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "pandas>=2.2.3",
    "parse>=1.20.2",
]

[tool.black]
line-length = 105
