#!groovy

pipeline {
  agent {
    node {
      label 'ssl_daintvm1'
    }
  }
  environment {
    OUTDIR = "/project/csstaff/rasolca/jenkins/DLA-Future/${env.BUILD_TAG}"
  }
  stages {
    stage('Checkout') {
      steps {
        deleteDir()
        checkout scm
      }
    }
    stage('Check format') {
      steps {
        sh '''
           echo "----- check format -----"
           sbatch --wait ci/check_format.sbatch
           '''
      }
    }
    stage('Compile') {
      parallel {
        stage('Compile mc Debug') {
          steps {
            sh '''
               ci/compile.sh daint-mc Debug
               '''
          }
        }
        stage('Compile mc Release') {
          steps {
            sh '''
               ci/compile.sh daint-mc Release
               '''
          }
        }
        stage('make doc') {
          steps {
            sh '''
               echo "----- make doc -----"
               export ENV=`realpath ci/daint-mc_env.sh`

               sbatch --wait ci/make-doc.sbatch
               '''
          }
        }
      }
    }
    stage('Test') {
      parallel {
        stage('Test mc Debug') {
          steps {
            sh '''
               ci/test.sh daint-mc Debug
               '''
          }
        }
        stage('Test mc Release') {
          steps {
            sh '''
               ci/test.sh daint-mc Release
               '''
          }
        }
      }
    }
  }

  post {
    always {
      sh '''
         mkdir ${OUTDIR}
         cp *.out.txt ${OUTDIR}
         '''
      archiveArtifacts artifacts: '**/*.out.txt', fingerprint: true
    }
  }
}
