#!/bin/bash -eu

if [[ $SLURM_PROCID == "0" ]]; then
    set -x
fi

pushd /DLA-Future-build > /dev/null

# Get commands of all tests, since we will run the commands directly under
# strace.
ctest -N
IFS=$'\n' all_tests=($(ctest $@ --show-only=json-v1 | jq --raw-output '.tests | map(.command) | .[] | join(" ")'))

num_failed_tests=0

export MKL_NUM_THREADS=5
export OMP_NUM_THREADS=5

for test in "${all_tests[@]}"; do
    # Run the tests, only output on the first rank
    if [[ $SLURM_PROCID == "0" ]]; then
        # Start the test once to get the number of threads that the pika
        # runtime is using. All ranks must start the test since MPI may be
        # initialized.  Only the first rank needs to check the number of
        # threads.
        set +e
        bash -c "$test --pika:exit --pika:print-bind"
        exit_code=$?
        [[ $exit_code -eq 1 ]] || exit $exit_code
        set -e
        num_threads=$(bash -c "$test --pika:exit --pika:print-bind" | grep 'PU L' | wc -l)
        echo "Using $num_threads threads"

        output_file=$(mktemp -u -t dlaf-test-output.tmp.XXXXXXXXXX)

        TZ=CET date +"Run started at: %H:%M:%S %z"
        strace -f -e clone3 bash -c "$test" |& tee $output_file
        TZ=CET date +"Run finished at: %H:%M:%S %z"

        num_threads_spawned=$(cat $output_file | grep 'clone3(' | wc -l)
        echo "$num_threads_spawned actually spawned"

        if (( num_threads_spawned != num_threads + 1 )); then
            num_failed_tests=$(( num_failed_tests + 1 ))
        fi
    else
        # --pika:exit exits the application with exit code 1. We only exit if
        # the error code is different than 1.
        set +e
        bash -c "$test --pika:exit" > /dev/null
        exit_code=$?
        [[ $exit_code -eq 1 ]] || exit $exit_code
        bash -c "$test --pika:exit" > /dev/null
        exit_code=$?
        [[ $exit_code -eq 1 ]] || exit $exit_code
        set -e
        bash -c $test > /dev/null
    fi
done

popd > /dev/null

exit $num_failed_tests
