#!/bin/bash

# Combine all reports into a single one
SHARED_REPORTS="$CI_PROJECT_DIR/codecov-reports"
TRACE_FILES=`find "$SHARED_REPORTS" -type f -iname '*.info'`
fastcov -C ${TRACE_FILES} --lcov -o "$SHARED_REPORTS/combined.info"

pushd /DLA-Future > /dev/null
codecov.sh -f "$SHARED_REPORTS/combined.info" -t $CODECOV_TOKEN_GITHUB
codecov.sh -f "$SHARED_REPORTS/combined.info" -t $CODECOV_TOKEN_GITLAB
popd > /dev/null
