#!/bin/bash
#
# Distributed Linear Algebra with Future (DLAF)
#
# Copyright (c) ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#

# Combine all reports into a single one
SHARED_REPORTS="$CI_PROJECT_DIR/codecov-reports"
TRACE_FILES=`find "$SHARED_REPORTS" -type f -iname '*.info'`
fastcov -C ${TRACE_FILES} --lcov -o "$SHARED_REPORTS/combined.info"

pushd /DLA-Future > /dev/null
codecov.sh -f "$SHARED_REPORTS/combined.info" -t $CODECOV_TOKEN_GITHUB
popd > /dev/null
