name: Inshepct

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  doc:
    runs-on: ubuntu-22.04

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y fd-find ripgrep
          wget -q https://github.com/tomwright/dasel/releases/download/v2.0.0/dasel-linux-amd64 -O /tmp/dasel
          sudo mv /tmp/dasel /usr/local/bin/dasel
          sudo chmod +x /usr/local/bin/dasel
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inshpect
        if: always()
        run: |
          export INSHPECT_NUMTHREADS=4
          export INSHPECT_FD=fdfind
          inshpect . .inshpect.toml
