name: Inshpect

on:
  pull_request:

jobs:
  inshpect:
    runs-on: ubuntu-24.04

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y fd-find ripgrep dasel

          pushd /tmp
          curl --output inshpect \
            --location https://raw.githubusercontent.com/msimberg/inshpect/d31ba8ed7e636c57cb9085ed3a8450d998e6b8a5/inshpect
          echo "4b891a178fa99ac800b9b92acc0596d72f640ca1ae6de7f35ac4b3785dcd7af9 inshpect" | sha256sum --check
          chmod +x inshpect
          mv inshpect /usr/local/bin/inshpect
          popd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inshpect
        if: always()
        run: |
          export INSHPECT_NUMTHREADS=4
          export INSHPECT_FD=fdfind
          inshpect . .inshpect.toml
